name: Docs Compile CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: npm ci
      - name: Build
        id: build
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build --if-present
      - name: Post-Build
        uses: actions/upload-artifact@v4
        with:
          name: avalonia-docs
          path: "/build"
